### PR TITLE
Support Yarn

### PR DESCRIPTION
**Pull request by anonrig**
Since I am using yarn for faster and more secure dependency management, I wanted to add Yarn support to native-navigation too.

### CODE REVIEW

**Comment by anonrig** [comment]
Can we get this merged? 🥇

**Comment by DovydasNavickas** [comment]
Are you sure you need yarn.lock committed into repository?

**Comment by anonrig** [comment]
Yes `yarn.lock` file is needed in order to find the hashes of the packages to check for validity and for speed purposes. @DovydasNavickas

**Comment by satya164** [comment]
`yarn.lock` should be committed to the repo, but don't think yarn uses it when installing this package. it shouldn't have any effect for consumers.

**Comment by anonrig** [comment]
Yarn readme states:

```
In order to get consistent installs across machines, Yarn needs more information than the dependencies you configure in your package.json. Yarn needs to store exactly which versions of each dependency were installed.

To do this Yarn uses a yarn.lock file in the root of your project.
```

https://yarnpkg.com/en/docs/yarn-lock

**Comment by henrikra** [comment]
@gpeal Should we merge this since everyone uses Yarn because it is so fast :D?

**Comment by jnbt** [comment]
@satya164 I agree with you. I'm using yarn for several projects, but yarn doesn't require the "consumed" packages to also include a `yarn.lock` file. To include a `yarn.lock` file would only be useful for the developers of this library.

**Comment by anonrig** [comment]
LOL

**Comment by JSafaiyeh** [comment]
@anonrig Relevant: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Pull request closed without merging**
